config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "campsites#index"
  get '/campsites/category', to: "campsites#category"
  resources :campsites do
    resources :comments, only: [:new, :create]
    resources :reviews, only: [:index, :create]
    collection do
      get 'search'
    end
  end
  # post 'campsite/:campsite_id/comment',to: 'comments#create', as: 'campsite_comment'
  post 'like/:id' ,to: 'likes#create', as: 'create_like'
  delete 'like/:id', to: 'likes#destroy', as: 'destroy_like'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/campsite.rb
class Campsite < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :genre
  belongs_to :prefecture
  belongs_to :status
  belongs_to :user
  has_one_attached :image

  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :reviews, dependent: :destroy
  
  validates :name,  presence: true
  validates :text,  presence: true
  validates :image, presence: true

  validates :genre_id, :prefecture_id, :status_id,  numericality: { other_than: 0 } 

  def self.search(search)
    if search != ""
      Campsite.where('text Like(?)', "%#{search}%")
    else
      Campsite.all
    end
  end

  def avg_score
    unless self.reviews.empty?
      reviews.average(:score).round(1).to_f
    else
      0.0
    end
  end
  def review_score_percentage
    unless self.reviews.empty?
      reviews.average(:score).round(1).to_f*100/5
    else
      0.0
    end
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :campsite
  belongs_to :user
end

app/models/genre.rb
class Genre < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: 'お風呂、シャワー有り' },
    { id: 3, name: '温泉施設有り' },
  ]

  include ActiveHash::Associations
  has_many :campsites
  
  end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :campsite
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' }, { id: 2, name: '北海道' }, { id: 3, name: '青森県' }, { id: 4, name: '岩手県' },
    { id: 5, name: '宮城県' }, { id: 6, name: '秋田県' }, { id: 7, name: '山形県' },
    { id: 8, name: '福島県' }, { id: 9, name: '茨城県' }, { id: 10, name: '栃木県' },
    { id: 11, name: '群馬県' }, { id: 12, name: '埼玉県' }, { id: 13, name: '千葉県' },
    { id: 14, name: '東京都' }, { id: 15, name: '神奈川県' }, { id: 16, name: '新潟県' },
    { id: 17, name: '富山県' }, { id: 18, name: '石川県' }, { id: 19, name: '福井県' },
    { id: 20, name: '山梨県' }, { id: 21, name: '長野県' }, { id: 22, name: '岐阜県' },
    { id: 23, name: '静岡県' }, { id: 24, name: '愛知県' }, { id: 25, name: '三重県' },
    { id: 26, name: '滋賀県' }, { id: 27, name: '京都府' }, { id: 28, name: '大阪府' },
    { id: 29, name: '兵庫県' }, { id: 30, name: '奈良県' }, { id: 31, name: '和歌山県' },
    { id: 32, name: '鳥取県' }, { id: 33, name: '島根県' }, { id: 34, name: '岡山県' },
    { id: 35, name: '広島県' }, { id: 36, name: '山口県' }, { id: 37, name: '徳島県' },
    { id: 38, name: '香川県' }, { id: 39, name: '愛媛県' }, { id: 40, name: '高知県' },
    { id: 41, name: '福岡県' }, { id: 42, name: '佐賀県' }, { id: 43, name: '長崎県' },
    { id: 44, name: '熊本県' }, { id: 45, name: '大分県' }, { id: 46, name: '宮崎県' },
    { id: 47, name: '鹿児島県' }, { id: 48, name: '沖縄県' }
  ]
  include ActiveHash::Associations
  has_many :campsites
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :campsite

  validates :score, presence: true
end

app/models/status.rb
class Status <  ActiveHash::Base
  self.data = [
    { id: 0, name: '--' },
    { id: 1, name: 'オートキャンプ' },
    { id: 2, name: '車乗り入れ不可' },
    { id: 3, name: 'ロッジ' },
    { id: 4, name: 'バンガロー' },
    { id: 5, name: 'キャビン' },
    { id: 6, name: '区画サイト' },
    { id: 7, name: 'フリーサイト' },
    { id: 8, name: 'フリーサイト、区画共に有り' },
    { id: 9, name: 'グランピング（手ぶらOK)' },
    { id: 10, name: 'フリー、区画サイト、バンガロー有り（オートキャンプ)' },
    { id: 11, name: 'フリー、区画サイト、バンガロー有り（オートキャンプ不可)' }
  ]
  
  include ActiveHash::Associations
  has_many :campsites
end

app/models/user.rb
class User < ApplicationRecord
  has_many :campsites
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true
  has_many :likes
  has_many :comments, dependent: :destroy
  has_many :reviews, dependent: :destroy
  
  def liked_by?(campsite_id)
    likes.where(campsite_id: campsite_id).exists?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['BASIC_AUTH_USER'] && password == ENV['BASIC_AUTH_PASSWORD']
    end
  end

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/campsites_controller.rb
class CampsitesController < ApplicationController
  before_action :set_campsite, only:[:destroy, :edit, :update, :show]
  before_action :authenticate_user!, except: [:index, :category, :search, :show]
  before_action :search_category_campsite, only: [:index, :category]

  def index
    @campsites = Campsite.includes(:user).order('created_at DESC')
  end

  def new
    @campsite = Campsite.new
  end

  def create
    @campsite = Campsite.new(campsite_params)
    # binding.pry
    if @campsite.valid?
       @campsite.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
   if @campsite.destroy
    redirect_to root_path
   else
    render :index
   end
  end

  def edit
  end

  def update
    if @campsite.update(campsite_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def show
    @campsite = Campsite.find(params[:id])
    @review = Review.new
    @comment = Comment.new
    @comments = @campsite.comments.includes(:user)
  end

  def category
      @campsite = @q.result
      status_id = params[:q][:status_id_eq]
  if @status = Status.find_by(id: status_id)
    else
      redirect_to root_path
    end
  end

  def search
    @campsites = Campsite.search(params[:keyword])
  end


  private 

  def campsite_params
    params.require(:campsite).permit(:name, :text, :image, :genre_id, :prefecture_id, :status_id).merge(user_id: current_user.id)
  end

  def set_campsite
    @campsite = Campsite.find(params[:id])
  end

  def search_category_campsite
    @q = Campsite.ransack(params[:q])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    # binding.pry
    comment = Comment.create(comment_params)
    redirect_to  campsite_path(comment.campsite.id)
  end

  private

  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, campsite_id: params[:campsite_id])
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  before_action :post_params

  def create
    Like.create(user_id: current_user.id, campsite_id: params[:id])
  end

  def destroy
    Like.find_by(user_id: current_user.id, campsite_id: params[:id]).destroy
  end

  private

  def post_params
    @campsite = Campsite.find(params[:id])
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @campsite = Campsite.find(params[:campsite_id])
    @reviews = @campsite.reviews
  end

  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    if @review.valid?
       @review.save
      redirect_to  campsite_reviews_path(@review.campsite)
    else
      @campsite = Campsite.find(params[:campsite_id])
      @comment = Comment.new
      render  "campsites/show"
    end

  end

  private

  def review_params
    params.require(:review).permit(:campsite_id, :score, :content)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campsites_helper.rb
module CampsitesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/campsites/_post.html.erb
   <% if user_signed_in? %>
            <% if current_user.liked_by?(@campsite.id) %>
             <div><%= link_to  destroy_like_path(@campsite.id), method: :DELETE, remote: true do %>
             <%= @campsite.likes.count %></div>
            <i class="far fa-heart unlike-btn" ></i>
            <%end%>
            <% else %>
            <div><%= link_to  create_like_path(@campsite.id), method: :POST, remote: true do %>
            <%= @campsite.likes.count %></div>
             <i class="fas fa-heart like-btn"></i>
              <% end %>
             <% end %>
            <%end %>

       

app/views/campsites/category.html.erb
<%# # 実装に必要な部分のみ記載しています %>
<html>
 <head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="toppage.css">
  </head>
<body>
<h2>カテゴリー <%= @status.name %></h2>
<div class='item-contents'>
    <ul class='item-lists'>
        <% @campsite.each do |campsite| %>
      <li class='list'>
        <%= link_to   campsite_path(campsite.id), method: :get do %> 
        <div class='item-img-content'>
         <%= image_tag campsite.image, class: "item-img" if campsite.image.attached? %>
         <ul class="more_list">
        </div>
        <%end%>
          <div class='item-info'>
          <h3 class='item-name'>
          <i class="fas fa-camera"></i>
            <%= "SITE NAME"  %><br>
            <%= campsite.name  %><br><br>
            <i class="fab fa-apple"></i>
            <%="サイト情報" %><br>
            <i class="fas fa-beer"></i>
            <%= "都道府県: #{campsite.prefecture.name}" %><br>
            <i class="fas fa-beer"></i>
            <%= "場内設備:" %>
            <br><%= campsite.genre.name %> <br>
            <i class="fas fa-beer"></i>
             <%= "施設タイプ:" %> 
             <br><%= campsite.status.name %><br><br>
          </h3>
          <%end %>
        </body>

app/views/campsites/edit.html.erb
<div class="contents row">
  <div class="container">
    <h3>編集する</h3>
    <%= form_with(model: @campsite, local: true) do |f| %>
    <div class="img-upload">
      <div class="weight-bold-text">
        <span class="indispensable">画像を選択してください</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
      <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {include_blank: "都道府県"}, {class:"genre-select"}) %><br>
       <%= f.collection_select(:genre_id, Genre.all, :id, :name, {include_blank:"場内設備"}, {class:"genre-select"}) %>
       <%= f.collection_select(:status_id,  Status.all, :id, :name, {include_blank: "施設タイプ"}, {class:"genre-select"}) %>
      <%= f.text_field :name, placeholder: "campsite name" %>
      <%= f.text_area :text, placeholder: "text", rows: "10" %>
      <%= f.submit "シェアする" %>
    <% end %>
  </div>
</div>

app/views/campsites/index.html.erb
<html>
 <head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="toppage.css">
    <title>Camp Site</title>
  </head>
  <body>
   <div class = "search-top">
     <div class= "search-center">
      <%= search_form_for @q, url: campsites_category_path do |f| %> 
      <%= f.collection_select :status_id_eq, Status.where.not(id: 0), :id, :name, include_blank: "カテゴリー検索" %>
      <%= button_tag :type => "submit", class: "btn" do %>
      <i class="fas fa-search-plus"></i>
      <%end%>
      <% end %>
      </div>
      <%= form_with(url: search_campsites_path,local: true, method: :get, class: "search-second") do |form| %> 
      <%= form.text_field :keyword, placeholder: "キーワード検索", class: "search-input" %>
         <%= button_tag :type => "submit", class: "btn" do %>
      <i class="fas fa-search-plus"></i>
      <%end%>
      <%end%>
    </div>

    <div class="contents">
      <div class="first-view">
    <%= image_tag  '/assets/トップページイラスト.png', alt: "トップ画面", class: "top-image" %>
      </div>
      <%# 商品一覧 %>
   
      
  <div class='item-contents'>
    <h1 class='title'>キャンプ場一覧</h1>
    <ul class='item-lists'>
      <% @campsites.each do |campsite| %>
      <li class='list'>
        <%= link_to  campsite_path(campsite.id), method: :get do %> 
        <div class='item-img-content'>
         <%= image_tag campsite.image, class: "item-img" if campsite.image.attached? %>
         <ul class="more_list">
        </div>
        <%end%>
        <div class='item-info'>
          <h3 class='item-name'>
          <i class="fas fa-camera"></i>
            <%= "SITE NAME"  %><br>
            <%= campsite.name  %><br><br>
            <i class="fab fa-apple"></i>
            <%="サイト情報" %><br>
            <i class="fas fa-beer"></i>
            <%= "都道府県: #{campsite.prefecture.name}" %><br>
            <i class="fas fa-beer"></i>
            <%= "場内設備:" %>
            <br><%= campsite.genre.name %> <br>
            <i class="fas fa-beer"></i>
             <%= "施設タイプ:" %> 
             <br><%= campsite.status.name %><br><br>
            
          </h3>
      
           <%end%>
           <div class='item-price'>
            <span><%= %><br><br><%= %></span> 
            <div class='star-btn'>
              <%# <%= image_tag "star.png", class:"star-icon" %> 
              <span class='star-count'></span>
            </div>
          </div>
        </div>
    </ul>
  </div>
  </body>
</html>

app/views/campsites/new.html.erb
<div class="contents row">
  <div class="container">
    <h3>シェアする</h3>
    <%= form_with(model: @campsite, local: true) do |f| %>
    <div class="img-upload">
      <div class="weight-bold-text">
        <span class="indispensable">画像を選択してください</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
       <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {include_blank: "都道府県"}, {class:"genre-select"}) %><br>
       <%= f.collection_select(:genre_id, Genre.all, :id, :name, {include_blank:"場内設備"}, {class:"genre-select"}) %>
       <%= f.collection_select(:status_id,  Status.all, :id, :name, {include_blank: "施設タイプ"}, {class:"genre-select"}) %>
       <%= f.text_field :name, placeholder: "キャンプ場名" %>
       <%= f.text_area :text, placeholder: "説明", rows: "10" %>
       <%= f.submit "send" %>
    <% end %>
  </div>
</div>

app/views/campsites/search.html.erb
   <div class='item-contents'>
    <ul class='item-lists'>
     <% @campsites.each do |campsite| %>
      <li class='list'>
          <%= link_to   campsite_path(campsite.id), method: :get do %> 
      <div class='item-img-content'>
          <%= image_tag campsite.image, class: "item-img" if campsite.image.attached? %>
      <ul class="more_list">
      </div>
        <%end%>
        <div class='item-info'>
           <i class="fas fa-camera"></i>
            <%= "SITE NAME"  %><br>
            <%= campsite.name  %><br><br>
            <i class="fab fa-apple"></i>
            <%="サイト情報" %><br>
            <i class="fas fa-beer"></i>
            <%= "都道府県: #{campsite.prefecture.name}" %><br>
            <i class="fas fa-beer"></i>
            <%= "場内設備:" %>
            <br><%= campsite.genre.name %> <br>
            <i class="fas fa-beer"></i>
             <%= "施設タイプ:" %> 
             <br><%= campsite.status.name %><br><br>
          </h3>
          <%end %>

app/views/campsites/show.html.erb
<div class="contents row">
  <%# <div class="content_post" > %>
    <div class="more">
   <%= image_tag @campsite.image.variant(resize: '400x500') %>
      <ul class="more_list">
     <% if user_signed_in? && current_user.id == @campsite.user_id %>
        <li>
          <%= link_to '編集', edit_campsite_path(@campsite.id), method: :get %>
        </li>
        <li>
          <%= link_to '削除', campsite_path(@campsite.id), method: :delete %> 
        </li>
        <%end%>
      </ul>
    </div>
   <div class='item-info'>
          <h3 class='item-name'>
       <i class="fas fa-camera"></i>
            <%= "SITE NAME"  %><br>
            <%= @campsite.name  %><br><br>
            <i class="fab fa-apple"></i>
            <%="サイト情報" %><br>
            <i class="fas fa-beer"></i>
            <%= "都道府県: #{@campsite.prefecture.name}" %><br>
            <i class="fas fa-beer"></i>
            <%= "場内設備:" %>
            <br><%= @campsite.genre.name %> <br>
            <i class="fas fa-beer"></i>
             <%= "施設タイプ:" %> 
             <br><%= @campsite.status.name %><br><br>
             <i class="fas fa-beer"></i>
            <%= "サイト紹介: #{@campsite.text}" %> 
            <br><br>

            <div id ="campsite_<%= @campsite.id %>">
              <%= render 'campsites/post', campsite: @campsite %>
              </div>
              <%= render 'reviews/form', review: @review, campsite: @campsite %>
            </div>
            <div class="container">
            <% if current_user %>
             <%= form_with model: [@campsite, @comment], local: true do |f| %>
             <%= f.text_area :text, placeholder: "コメントする", rows: "2" %>
             <%= f.submit "コメントする" %>
             <% end %>
             <% else %>
            <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
           <% end %>

          <div class="comments">
         <h4><コメント一覧></h4>
         <% if @comments %>
           <% @comments.each do |comment| %>
           <%= ":#{comment.user.nickname}" %>
            <p><%= comment.text %></p>
          <% end %> 
            <% end %>
         </div>


    

          
    
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CampSite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/91fc616da2.js" crossorigin="anonymous"></script>
  </head>

  <body>
       <header class="header">
      <div class="header__bar row">
        <h1 class="grid-6"><a href="/">local camp</a></h1>
        <% if user_signed_in? %>
        <div class="user_nav grid-6">
          <span><%= current_user.nickname %>
            <ul class="user__info">
              <li>
                <%= link_to "マイページ", "/users/#{current_user.id}" %>
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
              </li>
            </ul>
          </span>
          <%= link_to  new_campsite_path, class: 'btn btn-default' do %>
          <i class="fas fa-paper-plane"></i>
          <%end%>
          </div>
        <% else %>
          <div class="grid-6">
            <%= link_to "ログイン", new_user_session_path, class: "post" %>
            <%= link_to "新規登録", new_user_registration_path, class: "post" %>
          </div>
        <% end %>
      </div>
          <%# <%= search_form_for @q, url:  campsites_category_path do |f| %> 
         <%# <%= f.collection_select :genre_id_eq, Genre.where.not(id: 0), :id, :name, include_blank: "カテゴリー検索" %> 
        <%# <%= f.submit '検索' %> 
      <%# <% end %> 
    </header>
    <%= yield %>
    <footer>
        <p>
        Copyright Camp site 2020.
      </p>
    </footer>
  </body>
</html>

app/views/likes/create.js.erb
document.getElementById('campsite_<%= @campsite.id %>').innerHTML = '<%= j(render "campsites/post") %>'

app/views/likes/destroy.js.erb
document.getElementById('campsite_<%= @campsite.id %>').innerHTML = '<%= j(render "campsites/post") %>'

app/views/reviews/_form.html.erb
<p class="is-size-4 mb-3">レビューを書く</p>

<div class= "raiting-box mt-3">
  <%= form_with model: review, url: campsite_reviews_path(campsite), local: true do |f| %>
    <div class="main-rating">
      <div class="raiting mb-3">
       <span class="fa fa-star-o" id="star"></span>
       <span class="fa fa-star-o" id="star"></span>
       <span class="fa fa-star-o" id="star"></span>
       <span class="fa fa-star-o" id="star"></span>
       <span class="fa fa-star-o" id="star"></span>
      </div>
      <div class="ml-3 rating-value-display"><span id="rating-value-display">0</span>/5</div>
    </div>
    <%= f.hidden_field :campsite_id, value: campsite.id %>
    <%= f.hidden_field :score, id: "rating-value" %>
    <%= f.text_field :content, class: "textarea" %>
    <%= f.submit "保存", class: "button mt-3" %>
    <%= link_to "他のレビューをみる", campsite_reviews_path(campsite), class: "button light ml-3 mt-3" %>
  <%end%>
</div>

<%= javascript_include_tag 'reviews.js' %>

app/views/reviews/index.html.erb
<section class="section mt-6">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-5">
        <div class="card mb-6">
          <header class="card-header">
            <p class="card-header-title">
              <%= @campsite.name %>
            </p>
          </header>
          <div class="card-content">
            <div class="content average-score">
              <div class="star-rating mb-2">
                <div class="star-rating-front" style="width: <%= @campsite.review_score_percentage %>%">★★★★★</div>
                <div class="star-rating-back">★★★★★</div>
              </div>
              <div class="average-score-display ml-3 pt-2">
                <%= @campsite.avg_score %>点（<%= @campsite.reviews.count %>件のレビュー）
              </div>
            </div>
          </div>
        </div>
        <table class="table is-fullwidth has-text-centered">
          <thead>
            <tr>
              <th>ユーザー</th><th>点数</th><th>内容</th>
            </tr>
          </thead>
          <tbody>
            <% @reviews.each do |review| %>
              <tr>
                <td><%= review.user.nickname %></td>
                <td><%= review.score %></td>
                <td><%= review.content %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</section>